fail_fast: true
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
  - id: trailing-whitespace
  - id: debug-statements
  - id: check-added-large-files
    stages: [commit]

- repo: https://github.com/commitizen-tools/commitizen
  rev: v2.24.0
  hooks:
  - id: commitizen
    stages: [commit-msg]

- repo: https://github.com/asottile/pyupgrade
  rev: "v3.3.1"
  hooks:
  - id: pyupgrade
    args: [--py38-plus]

- repo: https://github.com/adamchainz/django-upgrade
  rev: "1.12.0"
  hooks:
  - id: django-upgrade
    args: [--target-version, "4.1"]

- repo: https://github.com/pre-commit/mirrors-yapf
  rev: v0.32.0
  hooks:
  - id: yapf
    stages: [commit]
    args:
    - --parallel
    - --in-place
    exclude: ^.*\b(migrations)\b.*$

- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
    - id: isort
      stages: [commit]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.942
  hooks:
  - id: mypy
    additional_dependencies: [
      django-stubs,
      types-freezegun,
      types-python-dateutil,
    ]
    stages: [commit]
